# ref - https://docs.github.com/en/enterprise-server@3.19/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations
name: Matrix Configuration

on:
    push:
    workflow_dispatch: 

jobs:
    deploy:
        strategy:
          # default behaviour to fail all jobs when one job fails
          # if false prevents GitHub from canceling all in-progress jobs if any matrix job fails. Default: true
          fail-fast: false
          # The maximum number of jobs that can run simultaneously when using a matrix job strategy. 
          # By default, GitHub will maximize the number of jobs run in parallel depending on runner availability.
          max-parallel: 2
          matrix: # there will be 3*2 = 6 jobs created
            os: [ubuntu-latest, ubuntu-20.04, windows-latest]
            images: [hello-world, alpine]
            exclude: # exclude any of the combination (ex: windows-latest, alpine)
              - images: alpine
                os: windows-latest
            include: # include other combination which are not part of combinations
              - images: amd64/alpine
                os: ubuntu-20.04
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo Docker Details
          run: docker info
        
        - name: Running image in ${{ matrix.os }}
          run: docker run ${{ matrix.images }}
    # commented out as using matrix
    # deploy-on-windows:
    #     runs-on: windows-latest
    #     steps:
    #     - name: Echo Docker details
    #       run: docker info

    #     - name: Run Images
    #       run: docker run hello-world