name: Exploring Variables and Secrets

on:
    workflow_dispatch:
    # schedule:
    #     - cron: "*/5 * * * *" 
    # push

env: # workflow scope level environment variables
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx
# workflow level concerrency
# concurrency: 
#     group: workflow-level-group # concerrency group name, can be any string expression
#     cancel-in-progress: true # can be any boolean expression. if true cancel any workflow runs and continue the new run
                             # if false new workflow run will wait for previous run to complete

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          # if variables at any level (env or repo level) not defined then an empty value is replaced and no error will be thrown
          # to access workflow env vars use env.<variable-name> or $<variable-name>
          # to access variables defined in github repo level, use vars.<variable-name>
          run: echo Docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

        - name: Docker Login
          # to access secrets defined at repo level use secrets.<secret-name>
          # secrets are encrypted and not displayed on the console
          run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        
        - name: Docker publish
          run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    deploy:
        needs: docker # will wait for docker job to complete
        concurrency: 
            group: production-deployment
            cancel-in-progress: true
        runs-on: ubuntu-latest
        steps:
            - name: Docker run
              run: |
                echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
                sleep 60