name: Exploring Variables and Secrets

on:
    workflow_dispatch:
    schedule:
        - cron: "*/5 * * * *" 
    # push

env: # workflow scope level environment variables
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          # if variables at any level (env or repo level) not defined then an empty value is replaced and no error will be thrown
          # to access workflow env vars use env.<variable-name> or $<variable-name>
          # to access variables defined in github repo level, use vars.<variable-name>
          run: echo Docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

        - name: Docker Login
          # to access secrets defined at repo level use secrets.<secret-name>
          # secrets are encrypted and not displayed on the console
          run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        
        - name: Docker publish
          run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest